Add OCSP and CRL support to certificate verify
smallstep/cli pull request #1161
Opened 2024-04-23 23:27 UTC by redrac

#### Name of feature:
Add OCSP and CRL support to certificate verify

#### Pain or issue this feature alleviates:
Add args and functionality to certificate verify to check a CRL and OCSP for a certificate based on the extensions. Users can pass flags to enable verification of each (CRL, OCSP). The command will try and get the CRL and OCSP server from the certificate extensions if the endpoints are not provided.

#### Supporting links/other PRs/issues:
Implements #845

#### Notes
- I tested the logic against a valid certificate, invalid OCSP/CRL endpoints, and a revoked certificate
- I moved some of the functions and structs from crl into its own internal package `internal/crlutil` so it can be reused
- Long term if [this](https://github.com/golang/go/issues/40017) ever is adressed then a lot of this can be removed in favor of using built in functionality in crypto/x509

2024-05-08 22:26 UTC, maraino requested changes
In most cases, if the certificate passed as a parameter contains an intermediate certificate, we can assume this is the issuer if the --ca flag is not provided.

2024-05-08 22:26 UTC, maraino commented on command/certificate/verify.go
> +		case crlEndpoint != "" && issuer.Equal(&x509.Certificate{}):
The second condition will be always false. If `issuerFile` is empty, `issuer` will be `nil`.

2024-05-08 22:26 UTC, maraino commented on command/certificate/verify.go
> +		if !issuer.Equal(&x509.Certificate{}) && !insecure {
I think this should be:
```suggestion
		if issuer != nil && !insecure {
```

2024-05-08 22:26 UTC, maraino commented on command/certificate/verify.go
> +	}
In most cases, the issuer for both the OCSP and CRL will be the same issuer of the certificate, so if the certificate passed as an argument contains an intermediate certificate, we might not need the issuer at all.

2024-05-08 22:26 UTC, maraino commented on command/certificate/verify.go
> +			endpoint = cert.OCSPServer[0]
We probably want to check against all of them. There will be only one in most cases.

2024-05-09 01:24 UTC, maraino commented on command/certificate/verify.go
> +			endpoint = cert.OCSPServer[0]
Sounds good

2024-05-14 18:24 UTC, maraino reviewed
Hi @redrac, I've added suggestion that I think solves all the linter errors, and renames the verbose flag to `--verbose`, I can apply those and merge, unless you see something wrong with my changes.

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +				Name:  "verify-verbose",
```suggestion
				Name:  "verbose, v",
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +		verbose          = ctx.Bool("verify-verbose")
```suggestion
		verbose          = ctx.Bool("verbose")
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +[**--issuing-ca**=<ca-cert-file>] [**--verify-verbose**]
```suggestion
[**--issuing-ca**=<ca-cert-file>] [**--verbose**]
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +			return errors.Errorf("could not verify certificate against OCSP server(s)")
```suggestion
			return errors.Errorf("could not verify certificate against CRL distribution point(s)")
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +func VerifyOCSPEndpoint(endpoint string, cert *x509.Certificate, issuer *x509.Certificate, httpClient *http.Client) (bool, error) {
```suggestion
func VerifyOCSPEndpoint(endpoint string, cert, issuer *x509.Certificate, httpClient *http.Client) (bool, error) {
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +func VerifyCRLEndpoint(endpoint string, cert *x509.Certificate, issuer *x509.Certificate, httpClient *http.Client, insecure bool) (bool, error) {
```suggestion
func VerifyCRLEndpoint(endpoint string, cert, issuer *x509.Certificate, httpClient *http.Client, insecure bool) (bool, error) {
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +				break
```suggestion
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +				break
```suggestion
```

2024-05-14 18:24 UTC, maraino commented on command/certificate/verify.go
> +		tlsConfig := &tls.Config{
```suggestion
		//nolint:gosec // using default configuration for 3rd party endpoints
		tlsConfig := &tls.Config{
```

2024-05-14 21:40 UTC, maraino approved these changes
lgtm

2024-05-14 21:41 UTC, merged

2024-05-15 11:04 UTC, hslatman commented
Late to the game, but is it an option to rename the flags to shorter versions, e.g. `--crl` and `--ocsp`? Given that they're used on the `verify` subcommand, I think the shorter names are sufficient. Or is it expected that those will be reused on (many) other subcommands in the future?