Add CSR common name to SANs if no other SANs are defined in CSR
smallstep/cli pull request #1172
Opened 2024-05-07 02:28 UTC by dopey

- Fixes #1779

2024-05-07 17:07 UTC, maraino requested changes

2024-05-07 17:07 UTC, maraino commented on command/certificate/sign.go
> +	}
I think we want to do this only if there are no SANs.

2024-05-07 17:07 UTC, maraino commented on command/certificate/sign.go
> +			},
Let's do something like `--omit-cn-san` as @hslatman suggested.

2024-05-07 21:05 UTC, hslatman submitted a review, later dismissed
Nice 😄

2024-05-07 22:01 UTC, maraino requested changes

2024-05-07 22:01 UTC, maraino commented on command/certificate/sign.go
> +		}
len(sans) is 0, so we don't need to do this. We can just do the following:

```suggestion
		sans = append(sans, cr.Subject.CommonName)
```

We might want to see what happens if the common name is empty and probably add a check for that.

2024-05-09 17:23 UTC, maraino approved these changes

2024-05-09 18:43 UTC, merged