Thread CA password decryption into offline CA bootstrap
smallstep/cli pull request #544
Opened 2021-09-08 21:55 UTC by dopey

Fixes #539.

2021-09-08 22:53 UTC, maraino requested changes
And I still see x5c and sshpop using `password-file` instead of `provisioner-password-file`
They should prefer that one, and fallback to `password-file`.

See:
https://github.com/smallstep/cli/blob/cce2ea8ef22610e3f13cb7391d9cad8afd62d9b7/utils/cautils/token_generator.go#L170
https://github.com/smallstep/cli/blob/cce2ea8ef22610e3f13cb7391d9cad8afd62d9b7/utils/cautils/token_generator.go#L208
https://github.com/smallstep/cli/blob/cce2ea8ef22610e3f13cb7391d9cad8afd62d9b7/utils/cautils/token_generator.go#L239-L244

2021-09-08 22:53 UTC, maraino commented on utils/cautils/offline.go
> +	fmt.Printf("stop")
remove debug statement

2021-09-09 00:26 UTC, maraino approved these changes
It looks good to me, but I think we should extract that switch logic to one private method so we can use it in the 3 cases:

It can be something like:
```go
func getProvisionerPasswordFile(ctx *cli.Context) (string, bool) {
	switch {
	case ctx.String("provisioner-password-file") != "":
		return ctx.String("provisioner-password-file"), true
	case ctx.String("password-file") != "":
		return ctx.String("password-file"), true
	default:
		return "", false
	}
}
```

Or if in all cases we are using the jose.WithPasswordFile, we can do `getProvisionerPasswordOptions(ctx *cli.Context) jose.Option`

2021-09-09 00:58 UTC, labichn commented
Works on my machine, thanks!

2021-09-09 06:43 UTC, merged