step crl inspect
smallstep/cli pull request #604
Opened 2022-01-08 00:46 UTC by maraino

### Description

This PR adds the new command `step crl inspect`. This command prints a crl in text, json, or PEM format.

2022-01-12 18:43 UTC, tashian requested changes
lgtm with a couple of small suggestions.

2022-01-12 18:43 UTC, tashian commented on command/crl/crl.go
> +certificate revocation list or CRL.
```suggestion
certificate revocation list (CRL).
```

2022-01-12 18:43 UTC, tashian commented on command/crl/inspect.go
> +		Usage:     "print certificate revocation list or CRL details in human readable format",
```suggestion
		Usage:     "print certificate revocation list (CRL) details in human-readable format",
```

2022-01-12 18:43 UTC, tashian commented on command/crl/inspect.go
> +		Description: `**step crl inspect** prints the details of a certificate revocation list (CRL).
```suggestion
		Description: `**step crl inspect** validates and prints the details of a certificate revocation list (CRL). 
A CRL is considered valid if its signature is valid, the CA is not expired, and the next update time is in the future.
```

2022-01-31 20:04 UTC, tashian commented on command/crl/inspect.go
> +:  The file or URL where the CRL is. If <--from> is passed it will inspect
```suggestion
:  The file or URL where the CRL is. If <--from> is passed, it will inspect
```

2022-01-31 20:04 UTC, tashian approved these changes

2022-02-01 02:53 UTC, dopey commented on command/crl/crl_extensions.go
> +func nexExtension(e pkix.Extension) Extension {
what is `nex`?

2022-02-01 03:02 UTC, dopey commented on command/crl/inspect.go
> +$ step crl inspect -ca ca.crt exampleca.crl
`--ca`

2022-02-01 03:11 UTC, dopey commented on command/crl/inspect.go
> +			println("foo")
remove this line

2022-02-01 03:13 UTC, dopey requested changes
see comments

2022-02-01 21:17 UTC, maraino commented on command/crl/inspect.go
> +			println("foo")
Fixed with 2911198

2022-02-01 21:18 UTC, maraino commented on command/crl/crl_extensions.go
> +func nexExtension(e pkix.Extension) Extension {
Fixed with 84c641c

2022-02-01 21:18 UTC, maraino commented on command/crl/inspect.go
> +$ step crl inspect -ca ca.crt exampleca.crl
Fixed with 117f131

2022-02-01 21:18 UTC, maraino commented on command/crl/inspect.go
> +    :  Print output in unstructured text suitable for a human to read.
Fixed with 4ac6c55

2022-02-01 21:55 UTC, dopey approved these changes
lgtm

2022-02-01 22:14 UTC, merged