Fix https://github.com/smallstep/cli/issues/627
smallstep/cli pull request #629
Opened 2022-02-09 08:37 UTC by henschkowski

### Description
I'm new to Go - this is my attempt to fix the issue #627 

💔Thank you!

2022-02-09 08:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smallstep/cli?pullRequest=629) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smallstep/cli?pullRequest=629) before we can accept your contribution.<br/><hr/>**Ralf Henschkowski** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smallstep/cli?pullRequest=629) it.</sub>

2022-02-09 19:57 UTC, dopey commented
@henschkowski, thanks for the PR! Would you mind signing our CLA please?

2022-02-09 22:32 UTC, henschkowski commented
Signed it .

Max ***@***.***> schrieb am Mi., 9. Feb. 2022, 20:57:

> @henschkowski <https://github.com/henschkowski>, thanks for the PR! Would
> you mind signing our CLA please?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/smallstep/cli/pull/629#issuecomment-1034139555>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACTD6FW3WG4T4UB76K2VLDU2LBJ5ANCNFSM5N4ZIB7Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-09 23:11 UTC, maraino requested changes
Hi @henschkowski, thanks for the PR, but can you change the condition.

2022-02-09 23:11 UTC, maraino commented on flags/flags.go
> +           !ctx.IsSet("offline") {
I would use `!ctx.Bool("offline")` because --offline=false is a valid option too.

2022-02-10 01:02 UTC, dopey commented
Pulled this into another PR to fix the conflict which is from something else we recently merged.

2022-02-10 01:02 UTC, closed without merging